// <auto-generated />
using System;
using System.Collections.Generic;
using GhostLetters.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GhostLetters.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GhostLettersDbContext))]
    [Migration("20261008024327_ChatCardNotes")]
    partial class ChatCardNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.AuthIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_identities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_identities_user_id");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_identities_provider_subject");

                    b.ToTable("auth_identities", "public");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.AwardNomination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<string>("NominationCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("nomination_code");

                    b.Property<Guid>("NominatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("nominator_id");

                    b.Property<Guid>("NomineeId")
                        .HasColumnType("uuid")
                        .HasColumnName("nominee_id");

                    b.HasKey("Id")
                        .HasName("pk_award_nominations");

                    b.HasIndex("GameId", "NominatorId")
                        .IsUnique()
                        .HasDatabaseName("ix_award_nominations_game_id_nominator_id");

                    b.ToTable("award_nominations", "public");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.AwardVote", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("uuid")
                        .HasColumnName("voter_id");

                    b.Property<Guid>("AwardNominationId")
                        .HasColumnType("uuid")
                        .HasColumnName("award_nomination_id");

                    b.HasKey("GameId", "VoterId")
                        .HasName("pk_award_votes");

                    b.HasIndex("AwardNominationId")
                        .HasDatabaseName("ix_award_votes_award_nomination_id");

                    b.ToTable("award_votes", "public");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ImageKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("image_key");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.Property<string>("Title")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_cards");

                    b.HasIndex("SetId", "ImageKey")
                        .IsUnique()
                        .HasDatabaseName("ix_cards_set_id_image_key");

                    b.ToTable("cards", "public");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.CardMark", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("CardId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("card_id");

                    b.Property<bool>("Believed")
                        .HasColumnType("boolean")
                        .HasColumnName("believed");

                    b.Property<int>("Checks")
                        .HasColumnType("integer")
                        .HasColumnName("checks");

                    b.Property<int>("Crosses")
                        .HasColumnType("integer")
                        .HasColumnName("crosses");

                    b.Property<string>("Sources")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("sources")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.HasKey("GameId", "OwnerId", "CardId")
                        .HasName("pk_card_marks");

                    b.ToTable("card_marks", "public");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.CardSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<bool>("IsBuiltin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_builtin");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_card_sets");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_card_sets_code");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_card_sets_owner_id");

                    b.ToTable("card_sets", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f1d0c2e-0001-4a11-9a00-000000000001"),
                            Code = "original",
                            IsBuiltin = true,
                            Title = "Оригинальный"
                        },
                        new
                        {
                            Id = new Guid("6f1d0c2e-0001-4a11-9a00-000000000002"),
                            Code = "mailbox",
                            IsBuiltin = true,
                            Title = "Почтовый ящик"
                        },
                        new
                        {
                            Id = new Guid("6f1d0c2e-0001-4a11-9a00-000000000003"),
                            Code = "ritual",
                            IsBuiltin = true,
                            Title = "Тайный ритуал"
                        },
                        new
                        {
                            Id = new Guid("6f1d0c2e-0001-4a11-9a00-000000000004"),
                            Code = "mirror",
                            IsBuiltin = true,
                            Title = "Зеркало истины"
                        });
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<List<string>>("CardIds")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("card_ids");

                    b.Property<List<string>>("CardNotes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("card_notes");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<int>("Round")
                        .HasColumnType("integer")
                        .HasColumnName("round");

                    b.Property<string>("Text")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("MediaId")
                        .HasDatabaseName("ix_chat_messages_media_id");

                    b.HasIndex("GameId", "CreatedAt")
                        .HasDatabaseName("ix_chat_messages_game_id_created_at");

                    b.ToTable("chat_messages", "public");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid?>("LobbyId")
                        .HasColumnType("uuid")
                        .HasColumnName("lobby_id");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phase");

                    b.Property<DateTimeOffset?>("PhaseDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("phase_deadline");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<int>("Seed")
                        .HasColumnType("integer")
                        .HasColumnName("seed");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.HasIndex("LobbyId")
                        .HasDatabaseName("ix_games_lobby_id");

                    b.HasIndex("Status", "PhaseDeadline")
                        .HasDatabaseName("ix_games_status_phase_deadline");

                    b.ToTable("games", "public");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.GameEventRecord", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("ClientCommandId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_command_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("visibility");

                    b.Property<Guid?>("VisibleTo")
                        .HasColumnType("uuid")
                        .HasColumnName("visible_to");

                    b.HasKey("GameId", "Seq")
                        .HasName("pk_game_events");

                    b.HasIndex("GameId", "ActorUserId", "ClientCommandId")
                        .HasDatabaseName("ix_game_events_game_id_actor_user_id_client_command_id")
                        .HasFilter("client_command_id IS NOT NULL");

                    b.ToTable("game_events", "public");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.GamePlayer", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("CharacterCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("character_code");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_connected");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<int>("Seat")
                        .HasColumnType("integer")
                        .HasColumnName("seat");

                    b.HasKey("GameId", "UserId")
                        .HasName("pk_game_players");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_game_players_user_id");

                    b.ToTable("game_players", "public");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.Like", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_user_id");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_user_id");

                    b.HasKey("GameId", "FromUserId", "ToUserId")
                        .HasName("pk_likes");

                    b.HasIndex("ToUserId")
                        .HasDatabaseName("ix_likes_to_user_id");

                    b.ToTable("likes", "public");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.Lobby", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentGameId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_game_id");

                    b.Property<Guid>("HostUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_user_id");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_lobbies");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_lobbies_code")
                        .HasFilter("status <> 'closed'");

                    b.HasIndex("HostUserId")
                        .HasDatabaseName("ix_lobbies_host_user_id");

                    b.ToTable("lobbies", "public");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.LobbyMember", b =>
                {
                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid")
                        .HasColumnName("lobby_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ready");

                    b.Property<string>("JoinMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("join_mode");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<int>("Seat")
                        .HasColumnType("integer")
                        .HasColumnName("seat");

                    b.HasKey("LobbyId", "UserId")
                        .HasName("pk_lobby_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_lobby_members_user_id");

                    b.ToTable("lobby_members", "public");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("storage_key");

                    b.HasKey("Id")
                        .HasName("pk_media");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_media_owner_id");

                    b.ToTable("media", "public");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.Nomination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_nominations");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_nominations_code");

                    b.ToTable("nominations", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f1d0c2e-0002-4a11-9a00-000000000001"),
                            Code = "steel_balls",
                            Description = "За самый дерзкий ход партии.",
                            IsActive = true,
                            Title = "Стальные яйца"
                        },
                        new
                        {
                            Id = new Guid("6f1d0c2e-0002-4a11-9a00-000000000002"),
                            Code = "sherlock",
                            Description = "Раньше всех понял, что произошло.",
                            IsActive = true,
                            Title = "Шерлок"
                        },
                        new
                        {
                            Id = new Guid("6f1d0c2e-0002-4a11-9a00-000000000003"),
                            Code = "best_liar",
                            Description = "Убедительнее всех водил следствие за нос.",
                            IsActive = true,
                            Title = "Лучший лжец"
                        },
                        new
                        {
                            Id = new Guid("6f1d0c2e-0002-4a11-9a00-000000000004"),
                            Code = "ghost_whisperer",
                            Description = "Лучше всех понимал подсказки Призрака.",
                            IsActive = true,
                            Title = "Голос Призрака"
                        });
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.PlayerNote", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<string>("Entries")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("entries");

                    b.Property<int>("Suspicion")
                        .HasColumnType("integer")
                        .HasColumnName("suspicion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("GameId", "OwnerId", "TargetUserId")
                        .HasName("pk_player_notes");

                    b.ToTable("player_notes", "public");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.PushToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("platform");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_push_tokens");

                    b.HasIndex("UserId", "Token")
                        .IsUnique()
                        .HasDatabaseName("ix_push_tokens_user_id_token");

                    b.ToTable("push_tokens", "public");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.RatingHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Delta")
                        .HasColumnType("integer")
                        .HasColumnName("delta");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<int>("RatingAfter")
                        .HasColumnType("integer")
                        .HasColumnName("rating_after");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_rating_history");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_rating_history_user_id_created_at");

                    b.ToTable("rating_history", "public");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", "public");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("avatar_color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsBot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_bot");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nickname");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AwardedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("awarded_at");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<string>("NominationCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("nomination_code");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Votes")
                        .HasColumnType("integer")
                        .HasColumnName("votes");

                    b.HasKey("Id")
                        .HasName("pk_user_achievements");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_achievements_user_id");

                    b.ToTable("user_achievements", "public");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.UserStats", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Games")
                        .HasColumnType("integer")
                        .HasColumnName("games");

                    b.Property<int>("LikesReceived")
                        .HasColumnType("integer")
                        .HasColumnName("likes_received");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("RoleWins")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("role_wins");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.HasKey("UserId")
                        .HasName("pk_user_stats");

                    b.HasIndex("Rating")
                        .HasDatabaseName("ix_user_stats_rating");

                    b.ToTable("user_stats", "public");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<int?>("Column")
                        .HasColumnType("integer")
                        .HasColumnName("column");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<string>("StageKind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("stage_kind");

                    b.Property<Guid?>("SuspectId")
                        .HasColumnType("uuid")
                        .HasColumnName("suspect_id");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("uuid")
                        .HasColumnName("voter_id");

                    b.HasKey("Id")
                        .HasName("pk_votes");

                    b.HasIndex("GameId", "Stage", "Attempt", "VoterId")
                        .IsUnique()
                        .HasDatabaseName("ix_votes_game_id_stage_attempt_voter_id");

                    b.ToTable("votes", "public");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.AuthIdentity", b =>
                {
                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_identities_users_user_id");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.AwardNomination", b =>
                {
                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_award_nominations_games_game_id");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.AwardVote", b =>
                {
                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.AwardNomination", null)
                        .WithMany()
                        .HasForeignKey("AwardNominationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_award_votes_award_nominations_award_nomination_id");

                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_award_votes_games_game_id");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.Card", b =>
                {
                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.CardSet", null)
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cards_card_sets_set_id");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.CardMark", b =>
                {
                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_card_marks_games_game_id");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.CardSet", b =>
                {
                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_card_sets_users_owner_id");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.ChatMessage", b =>
                {
                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_games_game_id");

                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.Media", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_chat_messages_media_files_media_id");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.Game", b =>
                {
                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.Lobby", null)
                        .WithMany()
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_games_lobbies_lobby_id");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.GameEventRecord", b =>
                {
                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_events_games_game_id");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.GamePlayer", b =>
                {
                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_players_games_game_id");

                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_game_players_users_user_id");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.Like", b =>
                {
                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_likes_games_game_id");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.Lobby", b =>
                {
                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("HostUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lobbies_users_host_user_id");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.LobbyMember", b =>
                {
                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.Lobby", null)
                        .WithMany()
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lobby_members_lobbies_lobby_id");

                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lobby_members_users_user_id");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.Media", b =>
                {
                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_users_owner_id");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.PlayerNote", b =>
                {
                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_notes_games_game_id");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.PushToken", b =>
                {
                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_push_tokens_users_user_id");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.RatingHistory", b =>
                {
                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rating_history_users_user_id");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.RefreshToken", b =>
                {
                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.UserAchievement", b =>
                {
                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_achievements_users_user_id");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.UserStats", b =>
                {
                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_stats_users_user_id");
                });

            modelBuilder.Entity("GhostLetters.Infrastructure.Persistence.Entities.Vote", b =>
                {
                    b.HasOne("GhostLetters.Infrastructure.Persistence.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_votes_games_game_id");
                });
#pragma warning restore 612, 618
        }
    }
}
